# Generated by Django 5.0.7 on 2024-07-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentregistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='21CS61', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.IntegerField(default=6),
        ),
    ]
